### PR TITLE
Always dump and load with little endianness

### LINKED ISSUE #2: Rewrite endianness if needed

### PR DESCRIPTION
**Pull request by jonatanklosko**
Closes #2.

### CODE REVIEW

**Review by grzuy — APPROVED** [review]
:100:

**Comment by jonatanklosko** [comment]
@grzuy can you transfer the package to the org with `mix hex.owner transfer safetensors elixir_nx`?

**Comment by grzuy** [comment]
Done :-) :+1:

**Comment by jonatanklosko** [comment]
Thanks! Published v0.1.1 :)

**Pull request merged**
